### ISSUE TITLE
[Pattern 2] Expose HTTP ports in Analytics nodes

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/pivotal-cf-apim#100]
**Description:**
HTTP port 9091, HTTPS 9444 need to be exposed in the current deployment as a new route. 

**Affected Product Version:**
APIM analytics 2.6.0

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/pivotal-cf-apim/pull/101.
