### ISSUE TITLE
Add minimum defaults to resource configuration

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/pivotal-cf-apim#102]
**Description:**
The followings are the current resource configurations to the tile.

```
    memory: 4096
    ephemeral_disk: 4096
    persistent_disk: 16384
    cpu: 2
    static_ip: 1
```
These are very high values and as they are given in the tile yaml, even though the user need to reduce them, it is not possible as they are set as minimum defaults.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/pivotal-cf-apim/pull/103.
