### ISSUE TITLE
Test BOSH Release for WSO2 API Manager deployment pattern 1

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/pivotal-cf-apim#26]
**Description:**
Created BOSH release needs to be tested in following environments.
1. Development environment using BOSH Lite.
2. Production environment

**Suggested Labels:**
Type/Task, Priority/High

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
2.1.0.2

**Related Issues:**
https://github.com/wso2/pivotal-cf-apim/issues/10

**Comment by imesh** [comment]
IMO this needs to be done as a part of task #16. Would there be any reason for creating a separate task for verifying the work which will be done in #16?
