### ISSUE TITLE
Refine the existing BOSH release implementation

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/pivotal-cf-apim#27]
**Description:**
For implementing BOSH releases for WSO2 API Manager product deployment patterns, the existing implementation is expected to be used as the building blocks. The current implementation building blocks require refinements.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
2.1.0.2

**Related Issues:**
https://github.com/wso2/pivotal-cf-apim/issues/10

**Comment by imesh** [comment]
Would you mind being more specific about the refinements? AFAIU, this is done in task #16.

**Comment by chirangaalwis** [comment]
@imesh this issue refers to the refinement of the scripts and other files which is part of the BOSH release. IMO, prior to creating the PCF Tile the implementation of the BOSH release need to be refined. Hence, I have added this as an independent issue.

**Comment by imesh** [comment]
Thanks Chiranga! May be we can refer the commits or pull requests of those changes in this issue.
