### ISSUE TITLE
Add support for API-M deployment pattern 1 in API-M BOSH release

### ISSUE THREAD

**Issue by imesh** [wso2/pivotal-cf-apim#5]
**Description:**
This task is to add support for API-M deployment pattern 1 in API-M BOSH release. It would need to use two BOSH jobs for API-M and Analytics, would need to implement templates and configuration parameters for applying configurations at the VM startup, handle dependencies between API-M and Analytics, use a MySQL Docker container for providing a central database for all API-M instances, handle the startup order, implement a bash script to do the complete deployment with BOSH Lite, etc.

**Affected Product Version:**
API-M v2.1.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04 LTS, MySQL v5.7, Oracle JDK v1.8, MySQL JDBC Driver v5.1.34

**Comment by bhathiya** [comment]
**Tasks completed so far**

1. Configured 1 APIM node and 1 Analytics node
2. Configured MySQL on docker

**Tasks to be done**

1. Configure 1 more node from each server with an LB
2.  Configure startup order
3. Upgrade Ubuntu stemcell
4. Update `deploy-all.sh` to automate all new changes.

**Comment by imesh** [comment]
Thanks @bhathiya for all your contributions on this. I'm closing this issue as we have another one created for the same purpose: #10.
