### ISSUE TITLE
[Pattern-2] Add Micro-gateway analytics support

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/pivotal-cf-apim#99]
**Description:**
Current deployment doesn't support Microgateway analytics. To support Microgateway analytics, it is required to add the database configuration mentioned in the documentation[1].

[1]https://docs.wso2.com/display/AM260/Configuring+APIM+Analytics#ConfiguringAPIMAnalytics-Step4-Configurethedatabases

**Affected Product Version:**
APIM 2.6.0

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/pivotal-cf-apim/pull/101.
